name: Python CI

on: 
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
  
    - name: Lint code
      run: pylint main.py
  
    - name: Run tests
      run: pytest
